# Instantaneous firing rate

We calculate the instantaneous firing rate of all neurons and save the results for later.

For convenience, we should get the same time resolution as the AnimalPose.pose data (50Hz).


In [1]:
%load_ext autoreload
%autoreload 2

%run ~/repo/autopi_analysis_bk/Jazi_et.al_2023_noInt/setup_project.py
%run ~/repo/autopi_analysis_bk/Jazi_et.al_2023_noInt/neuronAutopi.py

prepareSessionsForSpatialAnalysisProject(sSesList,myProject.sessionList)

Project name: autopi_ca1
dataPath: /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1
dlcModelPath: /adata/models
Reading /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/sessionList
We have 39 testing sessions in the list
See myProject and sSesList objects
Loading Animal_pose and Spike_train, sSes.ap and sSes.cg


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 39/39 [00:13<00:00,  2.99it/s]

Loading ses.trial_table_simple as ses.trials
Create condition intervals in ses.intervalDict


In [2]:
ses = myProject.sessionList[-1]
sSes = sSesList[-1]

In [3]:
fn = ses.path+"/navPathInstan.csv"
print("loading",fn)
pd.read_csv(fn)

loading /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn9686/mn9686-01112021-0106/navPathInstan.csv


name  trialNo       timeRos  timeRes  \
0             mn9686-01112021-0106_1-0_all        1  1.635781e+09  3057.72   
1             mn9686-01112021-0106_1-0_all        1  1.635781e+09  3057.74   
2             mn9686-01112021-0106_1-0_all        1  1.635781e+09  3057.76   
3             mn9686-01112021-0106_1-0_all        1  1.635781e+09  3057.78   
4             mn9686-01112021-0106_1-0_all        1  1.635781e+09  3057.80   
...                                    ...      ...           ...      ...   
172877  mn9686-01112021-0106_160-1_atLever      160  1.635786e+09  8393.02   
172878  mn9686-01112021-0106_160-1_atLever      160  1.635786e+09  8393.04   
172879  mn9686-01112021-0106_160-1_atLever      160  1.635786e+09  8393.06   
172880  mn9686-01112021-0106_160-1_atLever      160  1.635786e+09  8393.08   
172881  mn9686-01112021-0106_160-1_atLever      160  1.635786e+09  8393.10   

           iTime  iTimeProp   distance  distanceProp      speed          x  \
0       0.000000   0.000000   0.226477      0.000939  10.469781  -1.547535   
1       0.021631   0.002355   0.521394      0.002163  11.984293  -1.505792   
2       0.046240   0.005035   0.817749      0.003392  13.761295  -1.477743   
3       0.067775   0.007380   1.209617      0.005018  20.032589  -1.470911   
4       0.087337   0.009510   1.694762      0.007030  30.082162  -1.502748   
...          ...        ...        ...           ...        ...        ...   
172877  1.858261   0.950462  64.690139      0.965279  35.879708 -18.847819   
172878  1.879748   0.961452  65.473458      0.976967  36.726040 -18.781886   
172879  1.901077   0.972361  66.251160      0.988572  36.775143 -18.668076   
172880  1.922224   0.983178  67.017058      1.000000  23.287125 -18.505967   
172881  1.955114   1.000000  67.017058      1.000000        NaN -18.327809   

                y  targetDistance  targetToAnimalX  targetToAnimalY  \
0      -42.772820       43.748974        -0.886454       -49.407187   
1      -42.550224       43.525129        -0.844711       -49.184590   
2      -42.256644       43.230798        -0.816662       -48.891010   
3      -41.960367       42.934455        -0.809830       -48.594734   
4      -41.569795       42.545125        -0.841667       -48.204161   
...           ...             ...              ...              ...   
172877 -25.363831        8.941222       -15.222911        -1.085322   
172878 -26.131971        9.217626       -15.156978        -1.853462   
172879 -26.906977        9.511755       -15.043168        -2.628468   
172880 -27.667596        9.812199       -14.881058        -3.389087   
172881 -28.412486       10.123331       -14.702900        -4.133976   

        targetToAnimalAngle  cumSumDiffAngleAroundTarget  
0                 -1.588736                          NaN  
1                 -1.587969                     0.000767  
2                 -1.587499                     0.001238  
3                 -1.587460                     0.001276  
4                 -1.588255                     0.000481  
...                     ...                          ...  
172877            -3.070418                     4.739598  
172878            -3.019912                     4.790103  
172879            -2.968611                     4.841405  
172880            -2.917667                     4.892349  
172881            -2.867502                     4.942514  

[172882 rows x 16 columns]

In [4]:
sSes.ap.intervals.inter
a = np.arange(0.01,8465.98,0.02)
print("a:", a.shape,a.min(),a.max())
print("pose:",sSes.ap.pose.shape,sSes.ap.pose[:,0].min(),sSes.ap.pose[:,0].max())
myDiff = np.diff(a)
print("diff:",myDiff.min(),myDiff.max())


a: (423299,) 0.01 8465.97
pose: (423249, 8) 0.0 8464.96
diff: 0.019999999998617568 0.020000000000436557


We need to set all spike_train objects to the same time interval that covers all values of the AnimalPose.pose. The idea is to get a firing rate estimate for each position data, which are at 50 Hz.

In [5]:
def createInstantaneousFiringRateFile(sSes):
    inter = sSes.ap.intervals.inter.copy()
    inter[0,0]=0.01 # so that the times of ifr windows matches the ap.pose times
    print(inter)
    for n in sSes.cg.neuron_list:
        n.spike_train.set_intervals(inter)
    sSes.cg.instantaneous_firing_rate(bin_size_sec = 0.02, sigma = 1,free_memory=True)
    ifr,mids = sSes.cg.ifr
        
    
    myDiff = np.diff(mids)
    print("time range:",mids.min(),mids.max())
    print("time interval min and max:",myDiff.min(),myDiff.max())
    
    fn = sSes.path+"/ifr_autopi.pkl"
    print("saving",fn)
    with open(fn, 'wb') as outp:
        pickle.dump((ifr,mids), outp, pickle.HIGHEST_PROTOCOL)
    # to allow garbage collection, and avoid crashing out of RAM
    sSes.cg.ifr = None

In [6]:
createInstantaneousFiringRateFile(sSes)

[[1.00000e-02 8.46596e+03]]


57it [00:00, 64.17it/s]


time range: 0.02 8465.96
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn9686/mn9686-01112021-0106/ifr_autopi.pkl


## For all the sessions

In [7]:
for i,sSes in enumerate(sSesList):
    print(i,sSes.name)
    createInstantaneousFiringRateFile(sSes)

0 mn5824-20112020-0107
[[1.000000e-02 1.026168e+04]]


11it [00:00, 49.43it/s]


time range: 0.02 10261.68
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn5824/mn5824-20112020-0107/ifr_autopi.pkl
1 mn5824-22112020-0107
[[1.0000e-02 1.0229e+04]]


22it [00:00, 53.86it/s]


time range: 0.02 10229.0
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn5824/mn5824-22112020-0107/ifr_autopi.pkl
2 mn5824-24112020-0107
[[1.00000e-02 9.85056e+03]]


7it [00:00, 50.92it/s]

time range: 0.02 9850.56
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn5824/mn5824-24112020-0107/ifr_autopi.pkl


3 mn5824-02122020-0106
[[1.00000e-02 9.62484e+03]]


9it [00:00, 47.02it/s]

time range: 0.02 9624.84
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn5824/mn5824-02122020-0106/ifr_autopi.pkl


4 mn711-28012021-0106
[[1.00000e-02 8.35906e+03]]


10it [00:00, 55.76it/s]

time range: 0.02 8359.06
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn711/mn711-28012021-0106/ifr_autopi.pkl


5 mn711-30012021-0106
[[1.00000e-02 9.62214e+03]]


3it [00:00, 51.43it/s]


time range: 0.02 9622.14
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn711/mn711-30012021-0106/ifr_autopi.pkl
6 mn711-31012021-0107
[[1.000000e-02 1.142944e+04]]


21it [00:00, 37.11it/s]


time range: 0.02 11429.44
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn711/mn711-31012021-0107/ifr_autopi.pkl
7 mn711-01022021-0107
[[1.000000e-02 1.142684e+04]]


24it [00:00, 44.87it/s]


time range: 0.02 11426.84
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn711/mn711-01022021-0107/ifr_autopi.pkl
8 mn711-02022021-0108
[[1.000000e-02 1.203342e+04]]


22it [00:00, 41.56it/s]


time range: 0.02 12033.42
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn711/mn711-02022021-0108/ifr_autopi.pkl
9 mn711-03022021-0107
[[1.000000e-02 1.142948e+04]]


17it [00:00, 44.05it/s]


time range: 0.02 11429.48
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn711/mn711-03022021-0107/ifr_autopi.pkl
10 mn711-04022021-0107
[[1.000000e-02 1.202946e+04]]


22it [00:00, 40.35it/s]


time range: 0.02 12029.46
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn711/mn711-04022021-0107/ifr_autopi.pkl
11 mn2739-11022021-0107
[[1.0000e-02 9.5848e+03]]


7it [00:00, 50.76it/s]

time range: 0.02 9584.8
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn2739/mn2739-11022021-0107/ifr_autopi.pkl


12 mn2739-15022021-0105
[[1.00000e-02 6.69642e+03]]


16it [00:00, 87.78it/s]

time range: 0.02 6696.42
time interval min and max: 0.019999999999527063 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn2739/mn2739-15022021-0105/ifr_autopi.pkl


13 mn2739-16022021-0106
[[1.0000e-02 8.5312e+03]]


22it [00:00, 63.23it/s]


time range: 0.02 8531.2
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn2739/mn2739-16022021-0106/ifr_autopi.pkl
14 mn2739-17022021-0106
[[1.00000e-02 8.91486e+03]]


16it [00:00, 60.81it/s]


time range: 0.02 8914.86
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn2739/mn2739-17022021-0106/ifr_autopi.pkl
15 mn2739-21022021-0106
[[1.00000e-02 9.59562e+03]]


7it [00:00, 41.80it/s]


time range: 0.02 9595.62
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn2739/mn2739-21022021-0106/ifr_autopi.pkl
16 mn3246-09042021-0106
[[1.000000e-02 1.001206e+04]]


17it [00:00, 54.18it/s]


time range: 0.02 10012.06
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn3246/mn3246-09042021-0106/ifr_autopi.pkl
17 mn3246-10042021-0106
[[1.00000e-02 9.62436e+03]]


25it [00:00, 55.52it/s]


time range: 0.02 9624.36
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn3246/mn3246-10042021-0106/ifr_autopi.pkl
18 mn3246-12042021-0106
[[1.00000e-02 9.50932e+03]]


20it [00:00, 53.95it/s]


time range: 0.02 9509.32
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn3246/mn3246-12042021-0106/ifr_autopi.pkl
19 mn3246-14042021-0106
[[1.00000e-02 9.62462e+03]]


11it [00:00, 52.23it/s]


time range: 0.02 9624.62
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn3246/mn3246-14042021-0106/ifr_autopi.pkl
20 mn1173-02052021-0107
[[1.000000e-02 1.142772e+04]]


26it [00:00, 35.19it/s]


time range: 0.02 11427.72
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn1173/mn1173-02052021-0107/ifr_autopi.pkl
21 mn1173-06052021-0107
[[1.00000e-02 1.02268e+04]]


71it [00:01, 48.09it/s]


time range: 0.02 10226.8
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn1173/mn1173-06052021-0107/ifr_autopi.pkl
22 mn1173-08052021-0107
[[1.00000e-02 1.00306e+04]]


67it [00:01, 50.35it/s]


time range: 0.02 10030.6
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn1173/mn1173-08052021-0107/ifr_autopi.pkl
23 mn1173-09052021-0108
[[1.000000e-02 1.175442e+04]]


42it [00:00, 42.61it/s]


time range: 0.02 11754.42
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn1173/mn1173-09052021-0108/ifr_autopi.pkl
24 mn1173-11052021-0108
[[1.000000e-02 1.030658e+04]]


18it [00:00, 40.61it/s]


time range: 0.02 10306.58
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn1173/mn1173-11052021-0108/ifr_autopi.pkl
25 TYY9524-16082021-0106
[[1.00000e-02 9.68676e+03]]


3it [00:00, 51.46it/s]


time range: 0.02 9686.76
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/TYY9524/TYY9524-16082021-0106/ifr_autopi.pkl
26 TYY9524-18082021-0106
[[1.00000e-02 9.68522e+03]]


21it [00:00, 40.85it/s]


time range: 0.02 9685.22
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/TYY9524/TYY9524-18082021-0106/ifr_autopi.pkl
27 mn5618-07072021-0107
[[1.000000e-02 1.008534e+04]]


10it [00:00, 51.39it/s]


time range: 0.02 10085.34
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn5618/mn5618-07072021-0107/ifr_autopi.pkl
28 mn5618-12072021-0110
[[1.000000e-02 1.011462e+04]]


51it [00:01, 44.07it/s]


time range: 0.02 10114.62
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn5618/mn5618-12072021-0110/ifr_autopi.pkl
29 TYY5622-07092021-0106
[[1.0000e-02 9.6783e+03]]


88it [00:01, 51.99it/s]


time range: 0.02 9678.3
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/TYY5622/TYY5622-07092021-0106/ifr_autopi.pkl
30 TYY5622-17092021-0106
[[1.000e-02 9.687e+03]]


42it [00:00, 47.18it/s]


time range: 0.02 9687.0
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/TYY5622/TYY5622-17092021-0106/ifr_autopi.pkl
31 TYY5622-19092021-0106
[[1.000e-02 9.682e+03]]


39it [00:00, 53.52it/s]


time range: 0.02 9682.0
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/TYY5622/TYY5622-19092021-0106/ifr_autopi.pkl
32 TYY5622-20092021-0106
[[1.0000e-02 9.6904e+03]]


26it [00:00, 44.79it/s]


time range: 0.02 9690.4
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/TYY5622/TYY5622-20092021-0106/ifr_autopi.pkl
33 mn9686-20102021-0106
[[1.00000e-02 9.67754e+03]]


17it [00:00, 39.21it/s]


time range: 0.02 9677.54
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn9686/mn9686-20102021-0106/ifr_autopi.pkl
34 mn9686-26102021-0106
[[1.0000e-02 9.5698e+03]]


21it [00:00, 51.70it/s]


time range: 0.02 9569.8
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn9686/mn9686-26102021-0106/ifr_autopi.pkl
35 mn9686-27102021-0106
[[1.00000e-02 9.18946e+03]]


47it [00:00, 55.16it/s]


time range: 0.02 9189.46
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn9686/mn9686-27102021-0106/ifr_autopi.pkl
36 mn9686-28102021-0107
[[1.000000e-02 1.055598e+04]]


60it [00:01, 52.19it/s]


time range: 0.02 10555.98
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn9686/mn9686-28102021-0107/ifr_autopi.pkl
37 mn9686-29102021-0106
[[1.00000e-02 9.67986e+03]]


65it [00:01, 54.29it/s]


time range: 0.02 9679.86
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn9686/mn9686-29102021-0106/ifr_autopi.pkl
38 mn9686-01112021-0106
[[1.00000e-02 8.46596e+03]]


57it [00:00, 62.07it/s]


time range: 0.02 8465.96
time interval min and max: 0.019999999998617568 0.020000000000436557
saving /ext_drives/d80/Jazi_etal_2023_noInter/autopi_ca1/mn9686/mn9686-01112021-0106/ifr_autopi.pkl
